Elijah login system
cs-paz/ahch_app pull request #2
Opened 2021-07-06 18:57 UTC by ezwendel

Made a backend and frontend (needs work) for the login system.

Test: Can go to the url http://localhost:3000/login and enter the username johnIsCool and password reallyCoolGuy1 and login with no problems. If not using that account, there will be errors shown to the user.

2021-07-06 19:07 UTC, cs-paz requested changes

2021-07-06 19:07 UTC, cs-paz commented on tasks/seed.js
> +// let usersSchema = mongoose.Schema({
Remove this

2021-07-06 19:07 UTC, cs-paz commented on routes/login.js
> +    console.log('here')
remove this

2021-07-06 19:07 UTC, cs-paz commented on routes/login.js
> +      console.log(i)
remove this

2021-07-06 19:07 UTC, cs-paz commented on routes/login.js
> +      console.log(i.Username)
remove this

2021-07-06 19:07 UTC, cs-paz commented on routes/login.js
> +  console.log(req.body)
remove this

2021-07-06 19:07 UTC, cs-paz commented on routes/login.js
> +  console.log(username)
remove this

2021-07-06 19:07 UTC, cs-paz commented on routes/login.js
> +  console.log(password)
remove this

2021-07-06 19:07 UTC, cs-paz commented on data/users.js
> +// let usersSchema = mongoose.Schema({
remove this

2021-07-06 19:16 UTC, cs-paz approved these changes

2021-07-07 00:43 UTC, ashnarazdan123 reviewed
Started at http://localhost:3000/login and used username johnIsCool and password reallyCoolGuy1. Brought to message "error not found" at http://localhost:3000/home

If a different password or username entered "Username and/or password is incorrect" entered so that looks good. 

Something to note: if you remove the /home from url it brings you back to the http://localhost:3000 page with calendar without asking for another login.

2021-07-07 04:00 UTC, krixstin approved these changes

2021-07-07 04:00 UTC, krixstin commented on data/users.js
> +    // no clue what this does
I believe **.find()** method instantiates query, so it should let us use some searching parameters in {}, for like sorting or filtering later when needed

--->example from Geeksforgeeks 

// Only one parameter [query/condition]
// Find all documents that matches the
// condition name='Punit'
User.find(**{ name: 'Punit'}**, function (err, docs) {
    if (err){
        console.log(err);
    }
    else{
        console.log("First function call : ", docs);
    }
});

2021-07-07 15:09 UTC, merged